import { cookies } from "next/headers";

export interface MenuType {
  categoryId: number;
  categoryName: string;
  displayOrder: number;
  backgroundColor: string;
  productList: ProductType[];
}
export interface ProductType {
  storeProductId: number;
  storeProductName: string;
  storeProductPrice: number;
  discountPrice: number;
  displayOrder: number;
  productId: string;
  salePrice: number;
  productCode: string;
  productType: string;
  productName: string;
  optionGroupList: OptionGroupType[];
  storeProductCode: string;
}
interface OptionGroupType {
  optionGroupId: string;
  optionGroupName: string;
  minSelectCount: number;
  maxSelectCount: number;
  displayOrder: number;
  groupItemList: OptionItemType[];
}
interface OptionItemType {
  optionId: string;
  optionProductId: string;
}

export const getFontSize = async () => {
  const cookieStore = await cookies();
  const fontSize = cookieStore.get("fontSize")
    ? cookieStore.get("fontSize")?.value
    : "16";
  return Number(fontSize);
};

export const getMenus = async () => {
  const cookieStore = await cookies();
  const res = cookieStore.get("menus")
    ? JSON.parse(cookieStore.get("menus")?.value as string)
    : menus;


  return res;
};


const menus = [
  {
    categoryId: 3413,
    categoryName: "플레이트/세트",
    displayOrder: 1,
    backgroundColor: "#f5ce32",
    productList: [
      {
        storeProductId: 17660,
        storeProductName: "쇼핑백",
        storeProductPrice: 100,
        discountPrice: 0,
        displayOrder: 1,
        productId: "1025969",
        salePrice: 100,
        productCode: "P-202401221035023493",
        productType: "단품",
        productName: "쇼핑백",
        optionGroupList: [],
        storeProductCode: "1163535438",
      },
      {
        storeProductId: 17661,
        storeProductName: "스몰 플레이트",
        storeProductPrice: 9900,
        discountPrice: 0,
        displayOrder: 2,
        productId: "1035395",
        salePrice: 9900,
        productCode: "P-202402161044533815",
        productType: "세트",
        productName: "스몰 플레이트",
        optionGroupList: [
          {
            optionGroupId: "1002640",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012395",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012393",
                optionProductId: "1025930",
                optionName: "차오미엔",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012394",
                optionProductId: "1025929",
                optionName: "차오판",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
            ],
          },
          {
            optionGroupId: "1002641",
            optionGroupName: "메인",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012398",
                optionProductId: "1025932",
                optionName: "트러플블랙페퍼 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012397",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012706",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
              {
                optionId: "1012707",
                optionProductId: "1025935",
                optionName: "갈릭치킨 BBQ",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 4,
              },
              {
                optionId: "1012708",
                optionProductId: "1025936",
                optionName: "쓰리페퍼 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 5,
              },
              {
                optionId: "1012396",
                optionProductId: "1025937",
                optionName: "몽골리안 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 6,
              },
              {
                optionId: "1012399",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 1500,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 7,
              },
              {
                optionId: "1012709",
                optionProductId: "1025939",
                optionName: "사천 마파두부",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 8,
              },
              {
                optionId: "1012721",
                optionProductId: "1025942",
                optionName: "스프링롤",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 9,
              },
              {
                optionId: "1012997",
                optionProductId: "1025940",
                optionName: "망고크림 스퀴드",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 10,
              },
            ],
          },
        ],
        storeProductCode: "746991484",
      },
      {
        storeProductId: 17662,
        storeProductName: "레귤러 플레이트",
        storeProductPrice: 11900,
        discountPrice: 0,
        displayOrder: 3,
        productId: "1035407",
        salePrice: 11900,
        productCode: "P-202402161359139403",
        productType: "세트",
        productName: "레귤러 플레이트",
        optionGroupList: [
          {
            optionGroupId: "1002665",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012613",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012614",
                optionProductId: "1025930",
                optionName: "차오미엔",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012615",
                optionProductId: "1025929",
                optionName: "차오판",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
            ],
          },
          {
            optionGroupId: "1002666",
            optionGroupName: "메인",
            minSelectCount: 2,
            maxSelectCount: 2,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012616",
                optionProductId: "1025932",
                optionName: "트러플블랙페퍼 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012617",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012618",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
              {
                optionId: "1012619",
                optionProductId: "1025935",
                optionName: "갈릭치킨 BBQ",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 4,
              },
              {
                optionId: "1012620",
                optionProductId: "1025936",
                optionName: "쓰리페퍼 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 5,
              },
              {
                optionId: "1012621",
                optionProductId: "1025937",
                optionName: "몽골리안 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 6,
              },
              {
                optionId: "1012622",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 1500,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 7,
              },
              {
                optionId: "1012623",
                optionProductId: "1025939",
                optionName: "사천 마파두부",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 8,
              },
              {
                optionId: "1012624",
                optionProductId: "1025942",
                optionName: "스프링롤",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 9,
              },
              {
                optionId: "1013003",
                optionProductId: "1025940",
                optionName: "망고크림 스퀴드",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 10,
              },
            ],
          },
        ],
        storeProductCode: "674405232",
      },
      {
        storeProductId: 17663,
        storeProductName: "라지 플레이트",
        storeProductPrice: 14900,
        discountPrice: 0,
        displayOrder: 4,
        productId: "1035408",
        salePrice: 14900,
        productCode: "P-202402161401144430",
        productType: "세트",
        productName: "라지 플레이트",
        optionGroupList: [
          {
            optionGroupId: "1002667",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012627",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012628",
                optionProductId: "1025930",
                optionName: "차오미엔",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012629",
                optionProductId: "1025929",
                optionName: "차오판",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
            ],
          },
          {
            optionGroupId: "1002668",
            optionGroupName: "메인",
            minSelectCount: 3,
            maxSelectCount: 3,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012630",
                optionProductId: "1025932",
                optionName: "트러플블랙페퍼 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012631",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012632",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
              {
                optionId: "1012633",
                optionProductId: "1025935",
                optionName: "갈릭치킨 BBQ",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 4,
              },
              {
                optionId: "1012634",
                optionProductId: "1025936",
                optionName: "쓰리페퍼 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 5,
              },
              {
                optionId: "1012635",
                optionProductId: "1025937",
                optionName: "몽골리안 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 6,
              },
              {
                optionId: "1012636",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 1500,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 7,
              },
              {
                optionId: "1012637",
                optionProductId: "1025939",
                optionName: "사천 마파두부",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 8,
              },
              {
                optionId: "1012638",
                optionProductId: "1025942",
                optionName: "스프링롤",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 9,
              },
              {
                optionId: "1013004",
                optionProductId: "1025940",
                optionName: "망고크림 스퀴드",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 10,
              },
            ],
          },
        ],
        storeProductCode: "581225711",
      },
      {
        storeProductId: 17664,
        storeProductName: "(진열A) 오치+몽골",
        storeProductPrice: 11900,
        discountPrice: 0,
        displayOrder: 5,
        productId: "1035417",
        salePrice: 11900,
        productCode: "P-202402241204371589",
        productType: "세트",
        productName: "(진열A) 오치+몽골",
        optionGroupList: [
          {
            optionGroupId: "1002683",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012722",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
            ],
          },
          {
            optionGroupId: "1002684",
            optionGroupName: "메인",
            minSelectCount: 2,
            maxSelectCount: 2,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012723",
                optionProductId: "1025937",
                optionName: "몽골리안 포크",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
              {
                optionId: "1012724",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 2,
              },
            ],
          },
        ],
        storeProductCode: "665170022",
      },
      {
        storeProductId: 17665,
        storeProductName: "(진열B) BBQ+쓰리",
        storeProductPrice: 11900,
        discountPrice: 0,
        displayOrder: 6,
        productId: "1035418",
        salePrice: 11900,
        productCode: "P-202402241210324234",
        productType: "세트",
        productName: "(진열B) BBQ+쓰리",
        optionGroupList: [
          {
            optionGroupId: "1002685",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012725",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
            ],
          },
          {
            optionGroupId: "1002686",
            optionGroupName: "메인",
            minSelectCount: 2,
            maxSelectCount: 2,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012726",
                optionProductId: "1025936",
                optionName: "쓰리페퍼 포크",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
              {
                optionId: "1012727",
                optionProductId: "1025935",
                optionName: "갈릭치킨 BBQ",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 2,
              },
            ],
          },
        ],
        storeProductCode: "664246501",
      },
      {
        storeProductId: 17666,
        storeProductName: "(진열C) 레몬+쿵치",
        storeProductPrice: 11900,
        discountPrice: 0,
        displayOrder: 7,
        productId: "1035419",
        salePrice: 11900,
        productCode: "P-202402241234426146",
        productType: "세트",
        productName: "(진열C) 레몬+쿵치",
        optionGroupList: [
          {
            optionGroupId: "1002687",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012728",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
            ],
          },
          {
            optionGroupId: "1002688",
            optionGroupName: "메인",
            minSelectCount: 2,
            maxSelectCount: 2,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012729",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 1500,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
              {
                optionId: "1012730",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 2,
              },
            ],
          },
        ],
        storeProductCode: "663322980",
      },
      {
        storeProductId: 17667,
        storeProductName: "(진열D) BBQ+쿵치+몽골",
        storeProductPrice: 14900,
        discountPrice: 0,
        displayOrder: 8,
        productId: "1035420",
        salePrice: 14900,
        productCode: "P-202402241237171163",
        productType: "세트",
        productName: "(진열D) BBQ+쿵치+몽골",
        optionGroupList: [
          {
            optionGroupId: "1002689",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012731",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
            ],
          },
          {
            optionGroupId: "1002690",
            optionGroupName: "메인",
            minSelectCount: 3,
            maxSelectCount: 3,
            displayOrder: 2,
            groupItemList: [
              {
                optionId: "1012732",
                optionProductId: "1025937",
                optionName: "몽골리안 포크",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
              {
                optionId: "1012733",
                optionProductId: "1025935",
                optionName: "갈릭치킨 BBQ",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 2,
              },
              {
                optionId: "1012734",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 3,
              },
            ],
          },
        ],
        storeProductCode: "570143459",
      },
      //   ],
      // },
      // {
      //   categoryId: 3414,
      //   categoryName: "단품",
      //   displayOrder: 2,
      //   backgroundColor: "#f5ce32",
      //   productList: [
      // {
      //   storeProductId: 17668,
      //   storeProductName: "쇼핑백",
      //   storeProductPrice: 100,
      //   discountPrice: 0,
      //   displayOrder: 1,
      //   productId: "10259691",
      //   salePrice: 100,
      //   productCode: "P-202401221035023493",
      //   productType: "단품",
      //   productName: "쇼핑백",
      //   optionGroupList: [],
      //   storeProductCode: "1848970687",
      // },
      {
        storeProductId: 17669,
        storeProductName: "차오미엔",
        storeProductPrice: 5900,
        discountPrice: 0,
        displayOrder: 2,
        productId: "1025930",
        salePrice: 5900,
        productCode: "P-202401221035005122",
        productType: "단품",
        productName: "차오미엔",
        optionGroupList: [],
        storeProductCode: "1706626406",
      },
      {
        storeProductId: 17670,
        storeProductName: "차오판",
        storeProductPrice: 5900,
        discountPrice: 0,
        displayOrder: 3,
        productId: "1025929",
        salePrice: 5900,
        productCode: "P-202401221035004842",
        productType: "단품",
        productName: "차오판",
        optionGroupList: [],
        storeProductCode: "1707549927",
      },
      {
        storeProductId: 17671,
        storeProductName: "하프앤하프",
        storeProductPrice: 5900,
        discountPrice: 0,
        displayOrder: 4,
        productId: "1025931",
        salePrice: 5900,
        productCode: "P-202401221035005412",
        productType: "단품",
        productName: "하프앤하프",
        optionGroupList: [],
        storeProductCode: "1705702885",
      },
      {
        storeProductId: 17672,
        storeProductName: "[단품] 몽골리안포크 3,500",
        storeProductPrice: 3500,
        discountPrice: 0,
        displayOrder: 5,
        productId: "1035423",
        salePrice: 3500,
        productCode: "P-202402261951126003",
        productType: "단품",
        productName: "[단품] 몽골리안포크 3,500",
        optionGroupList: [],
        storeProductCode: "1603380945",
      },
      {
        storeProductId: 17673,
        storeProductName: "[단품] 레몬크림쉬림프 5,000",
        storeProductPrice: 5000,
        discountPrice: 0,
        displayOrder: 6,
        productId: "1035424",
        salePrice: 5000,
        productCode: "P-202402261951483296",
        productType: "단품",
        productName: "[단품] 레몬크림쉬림프 5,000",
        optionGroupList: [],
        storeProductCode: "1556329424",
      },
      {
        storeProductId: 17674,
        storeProductName: "[단품] 쿵파오치킨 3,500",
        storeProductPrice: 3500,
        discountPrice: 0,
        displayOrder: 7,
        productId: "1035425",
        salePrice: 3500,
        productCode: "P-202402261952310649",
        productType: "단품",
        productName: "[단품] 쿵파오치킨 3,500",
        optionGroupList: [],
        storeProductCode: "1601533903",
      },
      {
        storeProductId: 17675,
        storeProductName: "[단품] 트러플블랙페퍼치킨 3,500",
        storeProductPrice: 3500,
        discountPrice: 0,
        displayOrder: 8,
        productId: "1035426",
        salePrice: 3500,
        productCode: "P-202402261953016484",
        productType: "단품",
        productName: "[단품] 트러플블랙페퍼치킨 3,500",
        optionGroupList: [],
        storeProductCode: "1600610382",
      },
      {
        storeProductId: 17676,
        storeProductName: "[단품] 오렌지치킨 3,500",
        storeProductPrice: 3500,
        discountPrice: 0,
        displayOrder: 9,
        productId: "1035427",
        salePrice: 3500,
        productCode: "P-202402261953255183",
        productType: "단품",
        productName: "[단품] 오렌지치킨 3,500",
        optionGroupList: [],
        storeProductCode: "1599686861",
      },
      {
        storeProductId: 17677,
        storeProductName: "[단품] 쓰리페퍼포크 3,500",
        storeProductPrice: 3500,
        discountPrice: 0,
        displayOrder: 10,
        productId: "1035428",
        salePrice: 3500,
        productCode: "P-202402261953594683",
        productType: "단품",
        productName: "[단품] 쓰리페퍼포크 3,500",
        optionGroupList: [],
        storeProductCode: "1598763340",
      },
      {
        storeProductId: 17678,
        storeProductName: "[단품] 갈릭치킨 BBQ 3,500",
        storeProductPrice: 3500,
        discountPrice: 0,
        displayOrder: 11,
        productId: "1035429",
        salePrice: 3500,
        productCode: "P-202402261954253946",
        productType: "단품",
        productName: "[단품] 갈릭치킨 BBQ 3,500",
        optionGroupList: [],
        storeProductCode: "1597839819",
      },
      //   ],
      // },
      // {
      //   categoryId: 3415,
      //   categoryName: "팩",
      //   displayOrder: 3,
      //   backgroundColor: "#f5ce32",
      //   productList: [
      // {
      //   storeProductId: 17679,
      //   storeProductName: "쇼핑백",
      //   storeProductPrice: 100,
      //   discountPrice: 0,
      //   displayOrder: 1,
      //   productId: "1025969",
      //   salePrice: 100,
      //   productCode: "P-202401221035023493",
      //   productType: "단품",
      //   productName: "쇼핑백",
      //   optionGroupList: [],
      //   storeProductCode: "262991320",
      // },
      {
        storeProductId: 17680,
        storeProductName: "베이스 팩",
        storeProductPrice: 5900,
        discountPrice: 0,
        displayOrder: 2,
        productId: "1035409",
        salePrice: 5900,
        productCode: "P-202402161422140401",
        productType: "세트",
        productName: "베이스 팩",
        optionGroupList: [
          {
            optionGroupId: "1002669",
            optionGroupName: "베이스",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012641",
                optionProductId: "1025931",
                optionName: "하프앤하프",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012642",
                optionProductId: "1025930",
                optionName: "차오미엔",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012643",
                optionProductId: "1025929",
                optionName: "차오판",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
            ],
          },
        ],
        storeProductCode: "43473928",
      },
      {
        storeProductId: 17681,
        storeProductName: "레귤러 팩",
        storeProductPrice: 8900,
        discountPrice: 0,
        displayOrder: 3,
        productId: "1035413",
        salePrice: 8900,
        productCode: "P-202402161501250528",
        productType: "세트",
        productName: "레귤러 팩",
        optionGroupList: [
          {
            optionGroupId: "1002674",
            optionGroupName: "메인 3가지",
            minSelectCount: 3,
            maxSelectCount: 3,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012689",
                optionProductId: "1025932",
                optionName: "트러플블랙페퍼 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012690",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012691",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 3,
              },
              {
                optionId: "1012692",
                optionProductId: "1025935",
                optionName: "갈릭치킨 BBQ",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 4,
              },
              {
                optionId: "1012693",
                optionProductId: "1025936",
                optionName: "쓰리페퍼 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 5,
              },
              {
                optionId: "1012694",
                optionProductId: "1025937",
                optionName: "몽골리안 포크",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 6,
              },
              {
                optionId: "1012696",
                optionProductId: "1025939",
                optionName: "사천 마파두부",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 7,
              },
              {
                optionId: "1012697",
                optionProductId: "1025942",
                optionName: "스프링롤",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 8,
              },
              {
                optionId: "1012978",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 1500,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 9,
              },
              {
                optionId: "1013005",
                optionProductId: "1025940",
                optionName: "망고크림 스퀴드",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 10,
              },
            ],
          },
        ],
        storeProductCode: "139424012",
      },
      {
        storeProductId: 17682,
        storeProductName: "레몬크림 쉬림프",
        storeProductPrice: 11900,
        discountPrice: 0,
        displayOrder: 4,
        productId: "1025938",
        salePrice: 11900,
        productCode: "P-202401221035008281",
        productType: "단품",
        productName: "레몬크림 쉬림프",
        optionGroupList: [],
        storeProductCode: "71253129",
      },
      {
        storeProductId: 17683,
        storeProductName: "라지팩 (치킨)",
        storeProductPrice: 17300,
        discountPrice: 0,
        displayOrder: 5,
        productId: "1035414",
        salePrice: 17300,
        productCode: "P-202402161504593677",
        productType: "세트",
        productName: "라지팩 (치킨)",
        optionGroupList: [
          {
            optionGroupId: "1002675",
            optionGroupName: "치킨",
            minSelectCount: 2,
            maxSelectCount: 2,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012700",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012701",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
            ],
          },
        ],
        storeProductCode: "398664333",
      },
      {
        storeProductId: 17684,
        storeProductName: "라지팩 (쉬림프)",
        storeProductPrice: 23000,
        discountPrice: 0,
        displayOrder: 6,
        productId: "1035415",
        salePrice: 23000,
        productCode: "P-202402161505549922",
        productType: "세트",
        productName: "라지팩 (쉬림프)",
        optionGroupList: [
          {
            optionGroupId: "1002676",
            optionGroupName: "쉬림프",
            minSelectCount: 1,
            maxSelectCount: 1,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012702",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 1,
              },
            ],
          },
        ],
        storeProductCode: "574874254",
      },
      {
        storeProductId: 17685,
        storeProductName: "라지팩 (치킨&쉬림프)",
        storeProductPrice: 21000,
        discountPrice: 0,
        displayOrder: 7,
        productId: "1035416",
        salePrice: 21000,
        productCode: "P-202402161508050835",
        productType: "세트",
        productName: "라지팩 (치킨&쉬림프)",
        optionGroupList: [
          {
            optionGroupId: "1002677",
            optionGroupName: "치킨&쉬림프",
            minSelectCount: 2,
            maxSelectCount: 2,
            displayOrder: 1,
            groupItemList: [
              {
                optionId: "1012703",
                optionProductId: "1025933",
                optionName: "쿵파오 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 1,
              },
              {
                optionId: "1012704",
                optionProductId: "1025934",
                optionName: "오렌지 치킨",
                optionAddPrice: 0,
                optionQty: 0,
                defaultSelect: false,
                displayOrder: 2,
              },
              {
                optionId: "1012705",
                optionProductId: "1025938",
                optionName: "레몬크림 쉬림프",
                optionAddPrice: 0,
                optionQty: 1,
                defaultSelect: true,
                displayOrder: 3,
              },
            ],
          },
        ],
        storeProductCode: "514293775",
      },
      //   ],
      // },
      // {
      //   categoryId: 3416,
      //   categoryName: "사이드/음료",
      //   displayOrder: 4,
      //   backgroundColor: "#f5ce32",
      //   productList: [
      // {
      //   storeProductId: 17686,
      //   storeProductName: "쇼핑백",
      //   storeProductPrice: 100,
      //   discountPrice: 0,
      //   displayOrder: 1,
      //   productId: "1025969",
      //   salePrice: 100,
      //   productCode: "P-202401221035023493",
      //   productType: "단품",
      //   productName: "쇼핑백",
      //   optionGroupList: [],
      //   storeProductCode: "468740174",
      // },
      {
        storeProductId: 17687,
        storeProductName: "콜라",
        storeProductPrice: 2500,
        discountPrice: 0,
        displayOrder: 2,
        productId: "1025966",
        salePrice: 2500,
        productCode: "P-202401221035021292",
        productType: "단품",
        productName: "콜라",
        optionGroupList: [],
        storeProductCode: "539774411",
      },
      {
        storeProductId: 17688,
        storeProductName: "제로콜라",
        storeProductPrice: 2500,
        discountPrice: 0,
        displayOrder: 3,
        productId: "1025964",
        salePrice: 2500,
        productCode: "P-202401221035020082",
        productType: "단품",
        productName: "제로콜라",
        optionGroupList: [],
        storeProductCode: "537927369",
      },
      {
        storeProductId: 17689,
        storeProductName: "스프라이트",
        storeProductPrice: 2500,
        discountPrice: 0,
        displayOrder: 4,
        productId: "1025961",
        salePrice: 2500,
        productCode: "P-202401221035018358",
        productType: "단품",
        productName: "스프라이트",
        optionGroupList: [],
        storeProductCode: "535156806",
      },
      {
        storeProductId: 17690,
        storeProductName: "바오번",
        storeProductPrice: 1500,
        discountPrice: 0,
        displayOrder: 5,
        productId: "1025943",
        salePrice: 1500,
        productCode: "P-202401221035010748",
        productType: "단품",
        productName: "바오번",
        optionGroupList: [],
        storeProductCode: "487781428",
      },
    ],
  },
] 